repos:
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 2.3.5
  hooks:
    - id: sqlfluff-lint
      additional_dependencies: ['dbt-postgres', 'sqlfluff-templater-dbt']
    - id: sqlfluff-fix
      additional_dependencies: ['dbt-postgres', 'sqlfluff-templater-dbt']